### ISSUE TITLE
Col width adapted to content

### ISSUE THREAD

**Issue by chalbert** [JSxMachina/react-grid-system#101]
It doesn't seem possible to create a `<Col>` that adapts its width to its content.

This can be easily achieved with: `flex: 0` but it doesn't seem supported by `<Col>`.

In this example, we want the right column to take the size of its content, pushed to the right by the flexible left column.

```
|------------------------------------------------|-----------------------|
|   Logo  (Flexible column)                      |   Menu with x-items   |
|------------------------------------------------|-----------------------|
```

Would you welcome a PR?

I'm thinking of something like `<Col xs="content">` so it would be a non-breaking change.

The above example would then look like:

```
<Row>
  <Col><Logo /></Col>
  <Col xs="content"><Menu/></Col>
</Row>
```

**Comment by gerbenmeyer** [comment]
It's in the latest version (4.4.7) :smiley:
