### ISSUE TITLE
Missing Row option stretch of prop align in type definition

### ISSUE THREAD

**Issue by arielwb** [JSxMachina/react-grid-system#111]
In the docs (and the source) we should be able to pass the value stretch to the prop align:
https://github.com/JSxMachina/react-grid-system/blob/fea4d82faa983155694ca9d9c78d869ec4daeb29/src/grid/Row/index.jsx#L17

But this option is missing in the typescript definition file :(
https://github.com/JSxMachina/react-grid-system/blob/fea4d82faa983155694ca9d9c78d869ec4daeb29/index.d.ts#L4

**Comment by gerbenmeyer** [comment]
Added it :)
