### ISSUE TITLE
Supports className prop

### ISSUE THREAD

**Issue by ivolivares** [JSxMachina/react-grid-system#13]
Hi,

I try to use your react-grid-system but apparently not supports className as props. Any reason for it to be this way or something I did wrong?

Regards!

**Comment by tikider** [comment]
Indeed currently `className` is not one of the allowed props for any of the components made available by this library. 
Why would you want to be able to add a `className` to your grid components?

**Comment by gerbenmeyer** [comment]
This is now supported in the latest version, as well as all kind of other custom props! (Version 2.3.0)
