### ISSUE TITLE
iPad Pro

### ISSUE THREAD

**Issue by knipferrc** [JSxMachina/react-grid-system#16]
Another question regarding SSR. I used the mobile detect package and everything works great. The only issue I have is on iPad pro when rendering on the server I get a markup error. Can I set something in the breakpoints or something? Love this grid system by the way.

**Comment by gerbenmeyer** [comment]
What kind of error do you get? With the context type `breakpoints`, you can change the breakpoints if you want.

**Comment by knipferrc** [comment]
I get the markup between server and client are different. Only happens on iPad Pro when rendered on the server though.

**Comment by gerbenmeyer** [comment]
Probably it's because the mobile detect package detects an ipad pro as being a tablet, although it probably needs the desktop markup. This could be fixed if an ipad pro has a specific user agent, but I'm not sure about that.

**Comment by knipferrc** [comment]
Unfortunately I ran into too many issues and went with a basic css grid for now. Thanks for all your help, this package is great!

**Comment by abFx** [comment]
We ran to this issue ourselves while detecting the new samsung s7 device, so you need to add additional logic to determine if its really a mobile or a tablet or make PR to mobile detect to update some devices

**Comment by gerbenmeyer** [comment]
And only having the context types `phone` and `tablet` is also too limiting, we need something more fine-grained than that as well.

**Comment by gerbenmeyer** [comment]
Just made a start with that, by adding a context type `serverSideScreenClass`, replacing `phone` and `tablet`. All we need now is a better user agent analyzer :smile:

**Comment by gerbenmeyer** [comment]
I'll leave this outside the scope of this project.
