### ISSUE TITLE
Love this man! Would be cool if there was a "push / pull" implementation

### ISSUE THREAD

**Issue by danjonescidtrix** [JSxMachina/react-grid-system#17]
Absolutely love this repo, one thing I would love to see is something similar to bootstrap's "pull / push" col implementation... Just a thought 👀

**Comment by gerbenmeyer** [comment]
Good idea, I'll add that when I have the time :smile:

**Comment by danjonescidtrix** [comment]
That's cool man, I look forward to it!

**Comment by danjonescidtrix** [comment]
Sorry for re-opening, really think this would be a cool feature though... Will close off if you want?

**Comment by gerbenmeyer** [comment]
It's in there now, from version 2.8.0 :smile:

**Comment by danjonescidtrix** [comment]
That's dope man! - Props to you!
