### ISSUE TITLE
Allow ScreenCastRender to insert custom props into children

### ISSUE THREAD

**Issue by rogovdm** [JSxMachina/react-grid-system#20]
Not it's only possible to pass style props. Why not pass any prop?

````
style={screenSize => ...}
limitNumberOfItems = screenSize => ....
````

**Comment by rogovdm** [comment]
It's not rare that children has multiple props defining its' view. 

E.g material-ui's `Dialog`

[https://dl.dropboxusercontent.com/spa/sy5tiz1zn952c15/b-xqh6fw.png](Screenshot)

**Comment by gerbenmeyer** [comment]
Just fixed that, the props of the child element will now be passed as the second argument of the style function :smile:
