### ISSUE TITLE
Saving bundle size with targeted lodash imports

### ISSUE THREAD

**Issue by operatino** [JSxMachina/react-grid-system#21]
Hi,

Been reviewing our bundle size recently, on a project dependant on react-grid-system, and found that because of the transpiled code shipped with the component, we always get full `lodash` dependency without any tree-shaking.

The easiest fix we can do in this repo, is to import `lodash` methods directly from specific files like so:

```
import throttle from 'lodash/throttle';
```

This will enable other projects not using `lodash`, or using it partially with tree-shaking to save few hundred KB's in their bundles.

**Comment by csenn** [comment]
#23 should take care of this

**Comment by gerbenmeyer** [comment]
So it's there in the latest release :)

**Comment by csenn** [comment]
Great, thanks mate!
