### ISSUE TITLE
Center align?

### ISSUE THREAD

**Issue by cristianocca** [JSxMachina/react-grid-system#22]
Is it possible to center align the contents of a <Col> or <Row> object? Adding a manual style (textAlign: "center") to the object seems to break everything for some reason.

**Comment by gerbenmeyer** [comment]
That should just work fine. Can you provide an example of when it's not working?

**Comment by cristianocca** [comment]
It seems to be an issue with combined with material-ui components, the inner components inherit the text-align styles as well and gets all screwed.

**Comment by gerbenmeyer** [comment]
Ok, I'll close this then :)
