### ISSUE TITLE
Awesome work, why remove the render method of ScreenClassRender?

### ISSUE THREAD

**Issue by ahassanAt** [JSxMachina/react-grid-system#24]
I am currently, using the render method of ScreenClassRender; I am unable to update to .7 because the method was removed. Is there a reason for removing it?

**Comment by gerbenmeyer** [comment]
I removed it because AFAIK, it was unused and undocumented. If you really need it, I can put it back in the next version :)

**Comment by gerbenmeyer** [comment]
It's restored :smile:

**Comment by ahassanAt** [comment]
@gerbenmeyer thank you so much!!!
