### ISSUE TITLE
Updating breakpoints

### ISSUE THREAD

**Issue by gilesbutler** [JSxMachina/react-grid-system#25]
Sorry for the absolute n00b question!

I haven't used context types in React before and can't figure out how to update the breakpoints to something like `[576, 768, 800, 1200]`?

Thanks

**Comment by gerbenmeyer** [comment]
Just updated the example at https://github.com/JSxMachina/react-grid-system/blob/master/example/ExampleComponent.js to demonstrate this.

Hope it's clear now :smile:

**Comment by gilesbutler** [comment]
Thank you @gerbenmeyer that's a lot clearer now :) 

Sorry for the delayed response!
