### ISSUE TITLE
Not an issue (my apologies), but how do I set the gutterWidth in on a "Col"?

### ISSUE THREAD

**Issue by danjonescidtrix** [JSxMachina/react-grid-system#26]
Thank you in advance!

**Comment by danjonescidtrix** [comment]
Thank you in advance!

**Comment by gerbenmeyer** [comment]
You can do that by setting the `gutterWidth` context, in a similar way as the `breakpoints` context is set in the example component here: https://github.com/JSxMachina/react-grid-system/blob/master/example/ExampleComponent.js

Hope that helps :smile:

**Comment by danjonescidtrix** [comment]
Many thanks!
