### ISSUE TITLE
ScreenClassRender throws PropType validation warnings when using render

### ISSUE THREAD

**Issue by ngoss-eis** [JSxMachina/react-grid-system#27]
I've been using this library's `SecureClassRender` component to handle rendering (or not rendering) components based on state input, but I noticed that there are some PropType warnings being thrown when  according to the docs it doesn't seem like there should be any -- see below.

code:

> renderNavPanel(screenClass) {
>     //logic for displaying/not displaying
>     return shouldDisplay ? \<div>MARKUP HERE\</div> : null;
> }
> render() {
>     return \<ScreenClassRender render={this.renderNavPanel} />
> }

warning being thrown:
> Warning: Failed prop type: The prop `children` is marked as required in `ScreenClassRender`, but its value is `undefined`.
>    in ScreenClassRender (created by NavPanel)
>    in NavPanel(created by Connect(NavPanel))
>    in Connect(NavPanel) (created by Viewer)```

According to the [docs](https://jsxmachina.github.io/react-grid-system/#!/ScreenClassRender/), I was under the impression that if `render` was used, the children elements would be ignored. Is this the case? Or is the desired functionality here that I would still need to supply some child element to `ScreenClassRender`?

Thanks in advance!

**Comment by gerbenmeyer** [comment]
Thanks for the catch, it's fixed now in the last version, children are not required anymore.
