### ISSUE TITLE
providing contextTypes options example

### ISSUE THREAD

**Issue by Falieson** [JSxMachina/react-grid-system#28]
Hello! Thanks for this great reactive package, great features that are still hard to get in more standard packages.

I'm sure I'll figure it out before you respond, but others will probably appreciate an example of how to provide contextTypes to the Container component such as gutterWidth.

Thanks!

**Comment by gerbenmeyer** [comment]
The example application illustrates how to use contextTypes: https://github.com/JSxMachina/react-grid-system/tree/master/example

I'll also make this more clear in the readme :smile:
