### ISSUE TITLE
Unable to set the Col height to match Row height

### ISSUE THREAD

**Issue by aronlmin** [JSxMachina/react-grid-system#29]
Id like to request a boolean toggle be added to Col allowing for Col to be 100% of the height of the Row

right now I have this issue, and I have tried many ways to try to override it but cant get it to work...
the color blue is a Row element, the color red is a Col element
<img width="1440" alt="screen shot 2017-07-05 at 4 12 28 pm" src="https://user-images.githubusercontent.com/14061357/27888806-04aea39e-619d-11e7-8067-183eb957f360.png">

would be awesome, bootstrap has this feature [http://getbootstrap.com.vn/examples/equal-height-columns/](http://getbootstrap.com.vn/examples/equal-height-columns/)
:)

**Comment by kayneb** [comment]
You can pass in additional styles to `Col` using the prop `style`

**Comment by gerbenmeyer** [comment]
I'm considering to base the next major version on Flexbox, then it will be easily possible to support this. In the current setup, it's more complicated. But indeed, in the mean time you can pass additional styles using the `style` prop.
