### ISSUE TITLE
Would be great to have TypeScript @types definition

### ISSUE THREAD

**Issue by jugglingcats** [JSxMachina/react-grid-system#3]
... so we can use the lib with TypeScript ;)

**Comment by eldamir** [comment]
I agree. Cannot use this as is. needs TypeScript support

**Comment by gerbenmeyer** [comment]
Feel free to make a Pull Request, as I'm not using TypeScript myself :smile:

**Comment by cyberhck** [comment]
> Feel free to make a Pull Request, as I'm not using TypeScript myself

Does the statement still hold true?

**Comment by gerbenmeyer** [comment]
Yup :smile:

**Comment by jimthedev** [comment]
I put some types in #39 so head over there to give me feedback before I put in PR. Thanks!
