### ISSUE TITLE
When using Col, larger screen classes inherit styles that are calculated for smaller screen classes

### ISSUE THREAD

**Issue by kayneb** [JSxMachina/react-grid-system#30]
*Steps to reproduce:*
* Specify `12` as prop `xl`
* Specify `6` as prop `lg`
* Size the browser to `xl`

*Expected outcome:*
Col spans 100%

*Actual outcome:*
Col spans 50% (inheriting from `lg`)

**Comment by kayneb** [comment]
Perhaps this is intentional behaviour, in which case I think it makes sense to make a slightly different change. I'll raise two separate PRs and you can take your pick of which one makes sense.

**Comment by gerbenmeyer** [comment]
It's fixed in the latest version :smile:
