### ISSUE TITLE
Example with Next.js

### ISSUE THREAD

**Issue by rohmanhm** [JSxMachina/react-grid-system#33]
Will you enlarge example by using `Next.js`?

**Comment by gerbenmeyer** [comment]
How would that be different from any other React application?

**Comment by rohmanhm** [comment]
Actually they are the same, but with little different things.
Based on my experience, you cannot do something like this with `Next.js` https://github.com/JSxMachina/react-grid-system/blob/master/example/server.js#L25-L27

**Comment by mastepanoski** [comment]
You should do something like this:

<code>
  class AppPage extends React.Component {

    static getInitialProps({req}) {
      let userAgent
      if (process.browser) {
        userAgent = navigator.userAgent
      } else {
        userAgent = req.headers['user-agent']
      }

      const md = new MobileDetect(req.headers['user-agent'])
      let serverSideScreenClass = 'xl'
      if (md.phone() !== null) {
        serverSideScreenClass = 'xs'
      }
      if (md.tablet() !== null) {
        serverSideScreenClass = 'md'
      }

      return {userAgent, serverSideScreenClass}
    }

    render() {
      const {serverSideScreenClass} = this.props

      return (<ExampleComponent serverSideScreenClass={serverSideScreenClass}/>)
    }
 }
</code>

**Comment by gerbenmeyer** [comment]
Guess it's solved then :smile:

**Comment by FrencisAlreadyInUse** [comment]
After implementing I got this `Cannot read property 'headers' of undefined`. Anyone encountered this issue?

**Comment by FrencisAlreadyInUse** [comment]
```javaScript
class AppPage extends React.Component {
  static getInitialProps({req}) {
    let userAgent
    if (process.browser) {
      userAgent = navigator.userAgent
    } else {
      userAgent = req.headers['user-agent']
    }

    const md = new MobileDetect(userAgent)
    let serverSideScreenClass = 'xl'
    if (md.phone() !== null) {
      serverSideScreenClass = 'xs'
    }
    if (md.tablet() !== null) {
      serverSideScreenClass = 'md'
    }

    return {userAgent, serverSideScreenClass}
  }

  render() {
    const {serverSideScreenClass} = this.props

    return (<ExampleComponent serverSideScreenClass={serverSideScreenClass}/>)
  }
}
```

Resolved `undefined headers`
