### ISSUE TITLE
add src to npm package

### ISSUE THREAD

**Issue by SeanSilke** [JSxMachina/react-grid-system#34]
Hello @gerbenmeyer!
Would you consider to add src to npm package,
so it became possible to direct import components. 

Here [example](https://github.com/almende/vis#example-4-integrate-visjs-components-directly-in-your-webpack-build) from vis.js

**Comment by gerbenmeyer** [comment]
Sure, will do that in the next version

**Comment by gerbenmeyer** [comment]
And it's there :smile:
