### ISSUE TITLE
Why you fixate the version of react?

### ISSUE THREAD

**Issue by SeanSilke** [JSxMachina/react-grid-system#35]
Hello @gerbenmeyer!
The verson of React is hard fixate to "15.5.4", so when i bundle my project with webpack the react-grid-system include whole react for it self and can not use the existing.
In my package.json i have `"react": "^15.4.2",`
And actual react is 
![react dependend](https://user-images.githubusercontent.com/1077074/28846328-aaf8cc9e-7713-11e7-9e99-31ae58026af9.png)

Looks like hard fixate of react was not intentional.
here the [commit.](https://github.com/JSxMachina/react-grid-system/commit/4dbab1d754040a7e3d8888e84af827f3fa02d3b3) and it message is "remove gulp"
So before this commit you have the same dependence as i am.

**Comment by gerbenmeyer** [comment]
Indeed better to not hard fixate it, will change that :)

**Comment by gerbenmeyer** [comment]
Fixed, it's no longer fixed :smile:

**Comment by SeanSilke** [comment]
Thanks .Now the prod build is 100k lighter.
