### ISSUE TITLE
Build use react in un optimized (development) form.

### ISSUE THREAD

**Issue by SeanSilke** [JSxMachina/react-grid-system#36]
Build use react in un optimized (development) form.

Here the link what it is and how to use react prod build.
[facebook.github.io/react/docs/optimizing-performance.html](https://facebook.github.io/react/docs/optimizing-performance.html#use-the-production-build)
It is quite simple with webpack, you set environment var and minify react.
But I don't know how to do it only with babel.

**Comment by gerbenmeyer** [comment]
Would that matter? AFAIK we are only building the react-grid-system components.

**Comment by SeanSilke** [comment]
@gerbenmeyer you right it will not matter. Overall setting of the project will be used. The is no need to add this settings to component build.
Thanks for v2.9.5.

**Comment by gerbenmeyer** [comment]
:+1:
