### ISSUE TITLE
Adding xxs, xlg

### ISSUE THREAD

**Issue by torabian** [JSxMachina/react-grid-system#37]
In some projects I am using 2 additional sizes for smaller screens and larger screens, do you recommend if I add it into this repository?

**Comment by gerbenmeyer** [comment]
Personally, I think that 5 classes are currently sufficient.

**Comment by tonix-tuft** [comment]
It would be very useful to have the possibility of adding additional breakpoints, at least above the current `xl` breakpoint (e.g. `xxl` if a threshold of `1600px` is reached). On very large screens, it some layouts can look better this way.

**Comment by gerbenmeyer** [comment]
The main issue is that currently, the 5 classes are hard-coded. Adding one more (`xxl`) should be rather straightforward, but allowing a custom amount of classes would require a huge refactor.

**Comment by tonix-tuft** [comment]
https://github.com/sealninja/react-grid-system/issues/88#issuecomment-637401556
