### ISSUE TITLE
debug mode adds to the padding or margin of col

### ISSUE THREAD

**Issue by jamesjsewell** [JSxMachina/react-grid-system#38]
when in debug mode, along with the grey color, i also see a slight change in the padding/margin of the Col element. Is this a bug?

**Comment by jimthedev** [comment]
Looks like you are right:

https://github.com/JSxMachina/react-grid-system/blob/6c4956a1b77751066adf9137425480a43cc6225a/src/grid/Col/style.js#L32:L37

Would it be worth taking off the border & padding and using outline instead (it doesn't add any width);

**Comment by gerbenmeyer** [comment]
Yeah, it currently adds some padding on the top and bottom. The border should not add any width though, as the box sizing is set to `border-box`.

**Comment by gerbenmeyer** [comment]
Changed this in the last version, debug now only adds background and outline.
