### ISSUE TITLE
Render props

### ISSUE THREAD

**Issue by jimthedev** [JSxMachina/react-grid-system#44]
Would you be open to adding a render prop on each of the components so that instead of using the StyleClassRender HOC you could optionally just pass a render prop that then provided the styles? 

More on an example of this kind of method: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md#render-func

**Comment by abFx** [comment]
you mean like composing components and just adding that new prop?

**Comment by gerbenmeyer** [comment]
Why would this be a breaking feature? We can still also support having `children`, right?

**Comment by jimthedev** [comment]
@gerbenmeyer You're right, it could probably work w/o breaking things.

**Comment by gerbenmeyer** [comment]
So feel free to make a PR :smile: 
This actually also quite well aligns with my idea of moving the responsive utils to another package.

**Comment by gerbenmeyer** [comment]
I'll close this for now.

**Comment by jimthedev** [comment]
Yeah I may come back to this. Depends a bit on how work schedule goes. I will keep it in my backlog of things to do. :D
