### ISSUE TITLE
gutterWidth

### ISSUE THREAD

**Issue by Clcll** [JSxMachina/react-grid-system#47]
Where should I put gutterWidth prop ? 
I tried put in Container, Row, Col  components but it doesn't work.

Thx

**Comment by gerbenmeyer** [comment]
It's a context type now only, see also the example at https://github.com/gerbenmeyer/react-ssr-example/blob/master/components/Main.jsx on how to set context types.

I'm considering though to also add it as a prop to Row, instead of nogutter, but for now you have to use the context type.
