### ISSUE TITLE
lodash.throttle causes error when resizing browser quickly with Hidden Component.

### ISSUE THREAD

**Issue by isbdnt** [JSxMachina/react-grid-system#49]
![image](https://user-images.githubusercontent.com/26591233/33939120-e1777b2c-e044-11e7-9f5e-decb5ac73959.png)
![image](https://user-images.githubusercontent.com/26591233/33939224-44dbd1d6-e045-11e7-815f-acd57c3db9a9.png)

**Comment by gerbenmeyer** [comment]
Made a fix for that in the latest version (3.1.2). Please let me know if it still happens.
