### ISSUE TITLE
Col has overflow: 'hidden'

### ISSUE THREAD

**Issue by volkandkaya** [JSxMachina/react-grid-system#51]
https://github.com/JSxMachina/react-grid-system/blob/master/src/grid/Col/style.js

When was it added? 

Nothing major but it broke react-select when inside a Col.

**Comment by heineiuo** [comment]
I accidentally saw this. You can override it by prop `moreStyle:

https://github.com/JSxMachina/react-grid-system/blob/master/src/grid/Col/style.js#L19

**Comment by adeadman** [comment]
In my case I had to pass the `style` directive as an object:

```
render() {
  const columnStyle = {
    overflow: "hidden"
  }
  return(
    <Col style={columnStyle}>
      // content
    </Col>
  );
}
```

**Comment by gerbenmeyer** [comment]
You can indeed overwrite the `overflow:hidden` by passing style: `<Col style={{ overflow: 'visible' }}>...</Col>`. Hope this suffices for now.

**Comment by CharlyJazz** [comment]
Children with box shadow in a col with overflow hidden:

![image](https://user-images.githubusercontent.com/12489333/43651414-4d3ac508-9710-11e8-85a5-020b68f8caee.png)

With: `<Col style={{ overflow: 'visible' }}>`

![image](https://user-images.githubusercontent.com/12489333/43651427-5e244ce0-9710-11e8-9eaa-c98091e3c9c1.png)


What is the purposes of the overflow hidden in a col? :-1:

**Comment by gerbenmeyer** [comment]
No idea anymore what ever was the purpose of that. If there's no good reason to keep it, I'll remove it in the next version.

**Comment by CharlyJazz** [comment]
Thank you! I love this package. I have already used it in more than 12 applications in production. But in all I have to do "hacks" to avoid that hidden overflow.

**Comment by CharlyJazz** [comment]
Can I create a PR? :rabbit:

**Comment by gerbenmeyer** [comment]
Sure :+1:

**Comment by gerbenmeyer** [comment]
So, it's out in the latest version :smiley:
