### ISSUE TITLE
Unknown prop `nogutter` on <div> tag

### ISSUE THREAD

**Issue by sheez44** [JSxMachina/react-grid-system#52]
When using 'nogutter' i get this error in development:
`warning.js?6327:33 Warning: Unknown prop `nogutter` on <div> tag. Remove this prop from the element.` 

The functionality works but it clutters the console quite a lot.

**Comment by gerbenmeyer** [comment]
I can't reproduce this. Are you sure you're only adding `nogutter` to the `Row` component?

**Comment by gerbenmeyer** [comment]
Let me know if you still have this issue. Till then, I'll close this.

**Comment by sheez44** [comment]
It seems to fixed somehow
