### ISSUE TITLE
Bootstrap Grid Docs Link Broken

### ISSUE THREAD

**Issue by Koolstr** [JSxMachina/react-grid-system#53]
In your Readme, you give the link `http://getbootstrap.com/css/#grid`. However, the page redirects, which causes the anchor to disappear from the request. 

Update the link to `https://getbootstrap.com/docs/3.3/css/#grid`.

**Comment by gerbenmeyer** [comment]
Thanks for the catch, fixed it!

**Comment by Koolstr** [comment]
Took long enough, for something so simple lol
