### ISSUE TITLE
Remove/Disable clearfix element after last col (it is unnecessary)

### ISSUE THREAD

**Issue by Aretra** [JSxMachina/react-grid-system#54]
Is it possible to remove or to disable the clearfix element at the end of the row (after the last col)? It is unnecessary because the css property clear:both only works for floated elements and can not affect a flexbox grid.

Thanks!

**Comment by gerbenmeyer** [comment]
Good point, since the whole refactoring to flexbox, clearfix has no purpose. I removed it in the latest version.
