### ISSUE TITLE
IE11 Not Rendering Grid

### ISSUE THREAD

**Issue by FrencisAlreadyInUse** [JSxMachina/react-grid-system#62]
Hi @gerbenmeyer , 🥇 

Having some trouble rendering the grid system on IE11. It gets stuck on the initialising. 

I've tried the `setConfiguration({})` both in the `constructor` and `componentDidMount()`. Or the grid system renders, but totally broken or it doesn't render at all. (http://files.wild.as/fex1WG)

Do you have any clue?

**Comment by gerbenmeyer** [comment]
So you found out what was the issue?

**Comment by FrencisAlreadyInUse** [comment]
@gerbenmeyer was something wrong on my side. Thanks for responding
