### ISSUE TITLE
ScreenClassRender as HOC

### ISSUE THREAD

**Issue by ejh891** [JSxMachina/react-grid-system#66]
I've been using the `<ScreenClassRender />` (SCR) component a bunch, but recently ran into a bug in my code that took a little while to figure out because of the way that SCR works.

I was trying to use Radium to add a hover-state to an element like this:

```javascript
import { ScreenClassRender } from 'react-grid-system';
import Radium from 'radium';

function MyComponent(props) {
    return (
        <ScreenClassRender
            render={screenClass => {
                return (
                    <div
                        style={{ color: 'gray', ':hover': { color: 'blue' } }}
                     >
                         {screenClass}
                     </div>
                );
        />
    );
}

export default Radium(MyComponent);
```

But that didn't work. It took me a bit to figure out that the issue arose because Radium didn't actually process any of the elements inside of the render prop of SCR. My component was fairly large, so I didn't actually notice that the whole thing was inside of the SCR render method for a while. After realizing the issue, I was able to work around it, but it got me thinking about the api for SCR.

I now understand that this is the render-props pattern, but I wonder if it would make sense to provide a High Order Component option as well.

Usage might look like this:

```javascript
import { withScreenClass } from 'react-grid-system';
import Radium from 'radium';

function MyComponent(props) {
    const { screenClass } = props;

    return (
        <div
            style={{ color: 'gray', ':hover': { color: 'blue' } }}
         >
             {screenClass}
         </div>
   );
}

export default withScreenClass(Radium(MyComponent));
```

It feels a bit cleaner to me, so I thought I shoot out the idea. Any thoughts?

**Comment by ejh891** [comment]
Add #68 as a proposal

**Comment by gerbenmeyer** [comment]
I'm not completely sure yet. Isn't this actually an issue with Radium? And on the other hand I feel that we are duplicating a feature in this way.

**Comment by ejh891** [comment]
Yeah, I see what you mean. I think the real issue was that I was unfamiliar with the render-props pattern when I opened the issue, so I thought that it was a weird api.

Thanks for taking a look!

**Comment by chabou** [comment]
My 2 cents here.
I think this is a good thing to expose `screenClass` with render-prop pattern AND with an HOC. This is not really a feature duplication.

Some projects are using only HOC, and some others are using render-props only. I think this is better to be pattern agnostic. Like https://github.com/jaredpalmer/formik does, it would be great to have 3 way to access `screenClass` value :
 `<ScreenClassRender render>` `<ScreenClassRender children>` or `withScreenClass`  :)

BTW thank you for this really awesome project.
