### ISSUE TITLE
Please support a unique key prop on Rows

### ISSUE THREAD

**Issue by ajarbol** [JSxMachina/react-grid-system#70]
I often find myself wanting to map over arrays and render lists of Row components, please add a `key` property on the Row component that is applied to the outermost underlying `<div>` so I help React perform stable updates of the DOM as per https://reactjs.org/docs/lists-and-keys.html#keys

**Comment by gerbenmeyer** [comment]
As far as I know, this works out of the box for React components, without defining key explicitly.

**Comment by benlarkins** [comment]
I think this fixes the key issue you were referring to @ajarbol: https://github.com/JSxMachina/react-grid-system/commit/6895097ec6e136f6815a85c9901eed932f572435
I ran into the same thing and was about to put up a PR but then I saw it was fixed 3 hours ago.

**Comment by gerbenmeyer** [comment]
Guess I can close this then :smile:
