### ISSUE TITLE
Support for justify-content to horizontally align columns

### ISSUE THREAD

**Issue by mitramejia** [JSxMachina/react-grid-system#71]
Right now if I want to horizontally align columns inside a row I need to add a style tag, as expected this becomes cumbersome:

`<Row style={{ justifyContent: "center"}}>`

It would be nice to have something like:
`<Row justify="center">`
to achieve the same

Let me know if this is something feasible to begin working on a PR. Thank you!

**Comment by gerbenmeyer** [comment]
It's in the latest version!

**Comment by mitramejia** [comment]
Thank you!
