### ISSUE TITLE
Align column child

### ISSUE THREAD

**Issue by mitramejia** [JSxMachina/react-grid-system#76]
`Row` components are in charge of vertical alignment and horizontal alignment  of columns. But elements inside a columns can be aligned using the align prop like this:

`<Col align="left">child</Col>`

this align prop is missing in the docs and `index.d.ts` and I think it isn't handled in the codebase as well. Seems this is a beautiful accident.

**Comment by gerbenmeyer** [comment]
Yeah, unknown props are currently just passed to the actual html element, in this case the `<div>`. The align attribute is obsolete though, see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div#Attributes

So I'm not sure whether this is actually such a beautiful accident :smiley:
