### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by AntonioAsr** [JSxMachina/react-grid-system#77]
Hello,

Currently I am using react-grid-system for a website, but I am really struggling with some basic animations + react-great-system. Like pushing a column and moving it back to it's previous position with a transition.
Any advice - guidelines on how to process with this?
Any help is much appreciated, thanks!

**Comment by AntonioAsr** [comment]
@JSxMachina please could you provide some help for this?

**Comment by gerbenmeyer** [comment]
We don't really support something like that, but `push` and `pull` is implemented with style `left` and `right`. I guess you could put a css transition on that.
