### ISSUE TITLE
Ability to fixate grid to a container element, not screen

### ISSUE THREAD

**Issue by sandorvasas** [JSxMachina/react-grid-system#85]
We have a kind of complex application that needs to work on many screen sizes. I'm facing a case where I need to responsively align a grid of form fields which is displayed in a large, almost full screen dialog on medium screens, and a smaller sidebar on large screens. So even though the screen is larger, the container element is smaller and I'd need to break rows based on the size of the container, and not the screen.

Is there a solution, a workaround or a hack for this at the moment?

I.e. I can imagine something like having a 
```
<ResolutionProvider element="someElementId">
  <Container>
     <Row><Col>...etc, as usual</Col>...</Row>
     ...
  </Container>
</ResolutionProvider>
```

and `<Container/>` would receive the element dimensions instead of screen resolution.

**Comment by sandorvasas** [comment]
I just submitted a PR here: https://github.com/JSxMachina/react-grid-system/pull/86

Ended up using <Viewport /> which is basically a div. ResizeObserver listens to its dimension changes and all existing components consume that (top,left, width, height) tuple, overriding screen resolution if present.

**Comment by gerbenmeyer** [comment]
We just added the property `useOwnWidth` to `<ScreenClassProvider>`, which is doing exactly this. Hopefully this also suffices for you.
