### ISSUE TITLE
Col is LG when opened in XS

### ISSUE THREAD

**Issue by hmarcelodn** [JSxMachina/react-grid-system#89]
Hi,

I am experiencing a weird behaviour. I  have the following:

Mobile:
![screen shot 2018-11-02 at 11 13 54 am](https://user-images.githubusercontent.com/5897525/47920274-68d13c80-de90-11e8-9576-a0cb88eef23a.png)

Browser:
![screen shot 2018-11-02 at 11 13 05 am](https://user-images.githubusercontent.com/5897525/47920513-f7de5480-de90-11e8-866a-c5a2859a73c3.png)

```javascript
                 <Container fluid>
                    <Row>
                        <Col lg={6} xs={12}>
                            <div dangerouslySetInnerHTML={{ __html: this.props.text }}/>
                        </Col>
                    </Row>                    
                </Container>   
```

When I am in XS like an Android device, I am seing LG 6 columns instead of 12 as expected. Is this a bug? Do I need to use Visible for mobile devices instead?

Thanks

**Comment by LMulvey** [comment]
Which column are we looking at in the mobile version? Are you able to post more of your code/a link/reproducible example? You’re right-it should be using the xs column prop until it hits the lg breakpoint so I expect there is something else at play here. 

Is there possible another element extending the innerWidth of your body?

**Comment by minheq** [comment]
@LMulvey @hmarcelodn i could not create a reproduction but I solved it by adding:

```
setTimeout(() => {
  window.dispatchEvent(new Event('resize'));
}, 0);
```

**Comment by gerbenmeyer** [comment]
I'll close this then :)
