### ISSUE TITLE
<Col />

### ISSUE THREAD

**Issue by PaulieScanlon** [JSxMachina/react-grid-system#91]
Hi, i was wondering what the reason was for not having `display: 'flex'` on the `<Col />` component.

I was having a problem with children not stretching to fill the full height of the `<Col />`. Adding an inline style to `<Col />` solves this problem 

`<Col style={{display: 'flex}}/>`

... which is fine but is there a reason they are not `display: 'flex'` by default?

Thanks in advance. I like using react-grid-sytem it's a good lib!

**Comment by gerbenmeyer** [comment]
I suppose not necessary everybody wants to use flexbox inside the Col, so I don't think we have to enforce that.
