### ISSUE TITLE
ScreenClassProvider wrong typings 

### ISSUE THREAD

**Issue by ivanmjartan** [JSxMachina/react-grid-system#92]
Hi guys, 

I would like to use ScreenClassProvider in my typescript project but I guess that in index.d.ts or I do not understand what I am doing wrong 

I would like to use this like 

```
<ScreenClassProvider useOwnWidth={true}>
                <Container
                    fluid={true}
                    className={'s-fluid-layout gd-fluidlayout-container'}
                >
                    {this.generateRows()}
                </Container>
</ScreenClassProvider>
```

but I got this error 

>  TS2322: Type '{ children: Element; }' is not assignable to type 'Readonly<ScreenClassProviderProps>'.
>   Types of property 'children' are incompatible.

When I checked index.d.ts in ScreenClassProviderProps is not defined useOwnWidth and interface of component props look like:

```
type ScreenClassProviderProps = {
        children: Function
}
```

I am not sure but I think base on documentation interface of ScreenClassProviderProps should look like:

```
type ScreenClassProviderProps = {
        useOwnWidth: boolean
}
```

So am I doing something wrong? I am not sure how can I now use ScreenClassProvider correctly in my typescript project.

Thanks very much for your help

**Comment by conor909** [comment]
Same issue here:
<img width="503" alt="screenshot 2019-02-13 at 11 29 19" src="https://user-images.githubusercontent.com/2417359/52708672-a874ed80-2f82-11e9-9980-35c66c5800ed.png">

**Comment by ivanmjartan** [comment]
Hi, you can use a workaround like this

```
const ScreenClassManager = ScreenClassProvider as any;
<ScreenClassManager useOwnWidth={true}>
    ....
</ScreenClassManager>
```

**Comment by gerbenmeyer** [comment]
Not using typescript myself, so feel free to make a PR to fix this.

**Comment by loriamichele** [comment]
I've just opened a PR (#96) to fix the issue, hope it helps Typescript guys like me who also care about performance 🙌
