### ISSUE TITLE
Add support for multiple GutterWidths

### ISSUE THREAD

**Issue by xmile1** [JSxMachina/react-grid-system#97]
Hi, I am using react-grid-system in a project 👍 and I have a scenario where I need to set a different gutterWidth for different screen sizes(sm, md, lg, xl) just like it is for containerWidth. But checking thru the code it seems that possibility isnt implemented. 

I would like to propose an update to the config property `gutterWidth` such that it accepts an array just like `containerWidths` and definitely made backward compatible too.
e.g
`
setConfiguration({ gutterWidth:[5, 10, 15, 20] });
`

I would be happy to raise a PR if needed.

**Comment by gerbenmeyer** [comment]
Good idea, I guess it should support 5 values then (xs, sm, md, lg, xl). Would be happy to see the PR!

**Comment by gerbenmeyer** [comment]
We did add support for custom gutter widths per column, so like: `<Row gutterWidth={16}>`. Hope that will suffice for you, otherwise PR is still welcome :smiley:
